// Generated from Avro Phonetic Data
import Foundation

public struct AvroMatch {
    public let type: String      // "s" (suffix) or "p" (prefix)
    public let scope: String     // "p" (punctuation/bound), "v" (vowel), "c" (consonant), "e" (exact)
    public let negative: Bool
    public let value: String
}

public struct AvroRule {
    public let matches: [AvroMatch]
    public let replace: String
}

public struct AvroPattern {
    public let find: String
    public let replace: String
    public let rules: [AvroRule]?
}

public struct AvroData {
    public static let vowels: String = "aeiou"
    public static let consonants: String = "bcdfghjklmnpqrstvwxyz"
    public static let caseSensitive: String = "oiudgjnrstyz"

    public static let patterns: [AvroPattern] = [
        AvroPattern(find: "bhl", replace: "ভ্ল", rules: nil),
        AvroPattern(find: "psh", replace: "পশ", rules: nil),
        AvroPattern(find: "bdh", replace: "ব্ধ", rules: nil),
        AvroPattern(find: "bj", replace: "ব্জ", rules: nil),
        AvroPattern(find: "bd", replace: "ব্দ", rules: nil),
        AvroPattern(find: "bb", replace: "ব্ব", rules: nil),
        AvroPattern(find: "bl", replace: "ব্ল", rules: nil),
        AvroPattern(find: "bh", replace: "ভ", rules: nil),
        AvroPattern(find: "vl", replace: "ভ্ল", rules: nil),
        AvroPattern(find: "b", replace: "ব", rules: nil),
        AvroPattern(find: "v", replace: "ভ", rules: nil),
        AvroPattern(find: "cNG", replace: "চ্ঞ", rules: nil),
        AvroPattern(find: "cch", replace: "চ্ছ", rules: nil),
        AvroPattern(find: "cc", replace: "চ্চ", rules: nil),
        AvroPattern(find: "ch", replace: "ছ", rules: nil),
        AvroPattern(find: "c", replace: "চ", rules: nil),
        AvroPattern(find: "dhn", replace: "ধ্ন", rules: nil),
        AvroPattern(find: "dhm", replace: "ধ্ম", rules: nil),
        AvroPattern(find: "dgh", replace: "দ্ঘ", rules: nil),
        AvroPattern(find: "ddh", replace: "দ্ধ", rules: nil),
        AvroPattern(find: "dbh", replace: "দ্ভ", rules: nil),
        AvroPattern(find: "dv", replace: "দ্ভ", rules: nil),
        AvroPattern(find: "dm", replace: "দ্ম", rules: nil),
        AvroPattern(find: "DD", replace: "ড্ড", rules: nil),
        AvroPattern(find: "Dh", replace: "ঢ", rules: nil),
        AvroPattern(find: "dh", replace: "ধ", rules: nil),
        AvroPattern(find: "dg", replace: "দ্গ", rules: nil),
        AvroPattern(find: "dd", replace: "দ্দ", rules: nil),
        AvroPattern(find: "D", replace: "ড", rules: nil),
        AvroPattern(find: "d", replace: "দ", rules: nil),
        AvroPattern(find: "...", replace: "...", rules: nil),
        AvroPattern(find: ".`", replace: ".", rules: nil),
        AvroPattern(find: "..", replace: "।।", rules: nil),
        AvroPattern(find: ".", replace: "।", rules: nil),
        AvroPattern(find: "ghn", replace: "ঘ্ন", rules: nil),
        AvroPattern(find: "Ghn", replace: "ঘ্ন", rules: nil),
        AvroPattern(find: "gdh", replace: "গ্ধ", rules: nil),
        AvroPattern(find: "Gdh", replace: "গ্ধ", rules: nil),
        AvroPattern(find: "gN", replace: "গ্ণ", rules: nil),
        AvroPattern(find: "GN", replace: "গ্ণ", rules: nil),
        AvroPattern(find: "gn", replace: "গ্ন", rules: nil),
        AvroPattern(find: "Gn", replace: "গ্ন", rules: nil),
        AvroPattern(find: "gm", replace: "গ্ম", rules: nil),
        AvroPattern(find: "Gm", replace: "গ্ম", rules: nil),
        AvroPattern(find: "gl", replace: "গ্ল", rules: nil),
        AvroPattern(find: "Gl", replace: "গ্ল", rules: nil),
        AvroPattern(find: "gg", replace: "জ্ঞ", rules: nil),
        AvroPattern(find: "GG", replace: "জ্ঞ", rules: nil),
        AvroPattern(find: "Gg", replace: "জ্ঞ", rules: nil),
        AvroPattern(find: "gG", replace: "জ্ঞ", rules: nil),
        AvroPattern(find: "gh", replace: "ঘ", rules: nil),
        AvroPattern(find: "Gh", replace: "ঘ", rules: nil),
        AvroPattern(find: "g", replace: "গ", rules: nil),
        AvroPattern(find: "G", replace: "গ", rules: nil),
        AvroPattern(find: "hN", replace: "হ্ণ", rules: nil),
        AvroPattern(find: "hn", replace: "হ্ন", rules: nil),
        AvroPattern(find: "hm", replace: "হ্ম", rules: nil),
        AvroPattern(find: "hl", replace: "হ্ল", rules: nil),
        AvroPattern(find: "h", replace: "হ", rules: nil),
        AvroPattern(find: "jjh", replace: "জ্ঝ", rules: nil),
        AvroPattern(find: "jNG", replace: "জ্ঞ", rules: nil),
        AvroPattern(find: "jh", replace: "ঝ", rules: nil),
        AvroPattern(find: "jj", replace: "জ্জ", rules: nil),
        AvroPattern(find: "j", replace: "জ", rules: nil),
        AvroPattern(find: "J", replace: "জ", rules: nil),
        AvroPattern(find: "kkhN", replace: "ক্ষ্ণ", rules: nil),
        AvroPattern(find: "kShN", replace: "ক্ষ্ণ", rules: nil),
        AvroPattern(find: "kkhm", replace: "ক্ষ্ম", rules: nil),
        AvroPattern(find: "kShm", replace: "ক্ষ্ম", rules: nil),
        AvroPattern(find: "kxN", replace: "ক্ষ্ণ", rules: nil),
        AvroPattern(find: "kxm", replace: "ক্ষ্ম", rules: nil),
        AvroPattern(find: "kkh", replace: "ক্ষ", rules: nil),
        AvroPattern(find: "kSh", replace: "ক্ষ", rules: nil),
        AvroPattern(find: "ksh", replace: "কশ", rules: nil),
        AvroPattern(find: "kx", replace: "ক্ষ", rules: nil),
        AvroPattern(find: "kk", replace: "ক্ক", rules: nil),
        AvroPattern(find: "kT", replace: "ক্ট", rules: nil),
        AvroPattern(find: "kt", replace: "ক্ত", rules: nil),
        AvroPattern(find: "kl", replace: "ক্ল", rules: nil),
        AvroPattern(find: "ks", replace: "ক্স", rules: nil),
        AvroPattern(find: "kh", replace: "খ", rules: nil),
        AvroPattern(find: "k", replace: "ক", rules: nil),
        AvroPattern(find: "lbh", replace: "ল্ভ", rules: nil),
        AvroPattern(find: "ldh", replace: "ল্ধ", rules: nil),
        AvroPattern(find: "lkh", replace: "লখ", rules: nil),
        AvroPattern(find: "lgh", replace: "লঘ", rules: nil),
        AvroPattern(find: "lph", replace: "লফ", rules: nil),
        AvroPattern(find: "lk", replace: "ল্ক", rules: nil),
        AvroPattern(find: "lg", replace: "ল্গ", rules: nil),
        AvroPattern(find: "lT", replace: "ল্ট", rules: nil),
        AvroPattern(find: "lD", replace: "ল্ড", rules: nil),
        AvroPattern(find: "lp", replace: "ল্প", rules: nil),
        AvroPattern(find: "lv", replace: "ল্ভ", rules: nil),
        AvroPattern(find: "lm", replace: "ল্ম", rules: nil),
        AvroPattern(find: "ll", replace: "ল্ল", rules: nil),
        AvroPattern(find: "lb", replace: "ল্ব", rules: nil),
        AvroPattern(find: "l", replace: "ল", rules: nil),
        AvroPattern(find: "mth", replace: "ম্থ", rules: nil),
        AvroPattern(find: "mph", replace: "ম্ফ", rules: nil),
        AvroPattern(find: "mbh", replace: "ম্ভ", rules: nil),
        AvroPattern(find: "mpl", replace: "মপ্ল", rules: nil),
        AvroPattern(find: "mn", replace: "ম্ন", rules: nil),
        AvroPattern(find: "mp", replace: "ম্প", rules: nil),
        AvroPattern(find: "mv", replace: "ম্ভ", rules: nil),
        AvroPattern(find: "mm", replace: "ম্ম", rules: nil),
        AvroPattern(find: "ml", replace: "ম্ল", rules: nil),
        AvroPattern(find: "mb", replace: "ম্ব", rules: nil),
        AvroPattern(find: "mf", replace: "ম্ফ", rules: nil),
        AvroPattern(find: "m", replace: "ম", rules: nil),
        AvroPattern(find: "0", replace: "০", rules: nil),
        AvroPattern(find: "1", replace: "১", rules: nil),
        AvroPattern(find: "2", replace: "২", rules: nil),
        AvroPattern(find: "3", replace: "৩", rules: nil),
        AvroPattern(find: "4", replace: "৪", rules: nil),
        AvroPattern(find: "5", replace: "৫", rules: nil),
        AvroPattern(find: "6", replace: "৬", rules: nil),
        AvroPattern(find: "7", replace: "৭", rules: nil),
        AvroPattern(find: "8", replace: "৮", rules: nil),
        AvroPattern(find: "9", replace: "৯", rules: nil),
        AvroPattern(find: "NgkSh", replace: "ঙ্ক্ষ", rules: nil),
        AvroPattern(find: "Ngkkh", replace: "ঙ্ক্ষ", rules: nil),
        AvroPattern(find: "NGch", replace: "ঞ্ছ", rules: nil),
        AvroPattern(find: "Nggh", replace: "ঙ্ঘ", rules: nil),
        AvroPattern(find: "Ngkh", replace: "ঙ্খ", rules: nil),
        AvroPattern(find: "NGjh", replace: "ঞ্ঝ", rules: nil),
        AvroPattern(find: "ngOU", replace: "ঙ্গৌ", rules: nil),
        AvroPattern(find: "ngOI", replace: "ঙ্গৈ", rules: nil),
        AvroPattern(find: "Ngkx", replace: "ঙ্ক্ষ", rules: nil),
        AvroPattern(find: "NGc", replace: "ঞ্চ", rules: nil),
        AvroPattern(find: "nch", replace: "ঞ্ছ", rules: nil),
        AvroPattern(find: "njh", replace: "ঞ্ঝ", rules: nil),
        AvroPattern(find: "ngh", replace: "ঙ্ঘ", rules: nil),
        AvroPattern(find: "Ngk", replace: "ঙ্ক", rules: nil),
        AvroPattern(find: "Ngx", replace: "ঙ্ষ", rules: nil),
        AvroPattern(find: "Ngg", replace: "ঙ্গ", rules: nil),
        AvroPattern(find: "Ngm", replace: "ঙ্ম", rules: nil),
        AvroPattern(find: "NGj", replace: "ঞ্জ", rules: nil),
        AvroPattern(find: "ndh", replace: "ন্ধ", rules: nil),
        AvroPattern(find: "nTh", replace: "ন্ঠ", rules: nil),
        AvroPattern(find: "NTh", replace: "ণ্ঠ", rules: nil),
        AvroPattern(find: "nth", replace: "ন্থ", rules: nil),
        AvroPattern(find: "nkh", replace: "ঙ্খ", rules: nil),
        AvroPattern(find: "ngo", replace: "ঙ্গ", rules: nil),
        AvroPattern(find: "nga", replace: "ঙ্গা", rules: nil),
        AvroPattern(find: "ngi", replace: "ঙ্গি", rules: nil),
        AvroPattern(find: "ngI", replace: "ঙ্গী", rules: nil),
        AvroPattern(find: "ngu", replace: "ঙ্গু", rules: nil),
        AvroPattern(find: "ngU", replace: "ঙ্গূ", rules: nil),
        AvroPattern(find: "nge", replace: "ঙ্গে", rules: nil),
        AvroPattern(find: "ngO", replace: "ঙ্গো", rules: nil),
        AvroPattern(find: "NDh", replace: "ণ্ঢ", rules: nil),
        AvroPattern(find: "nsh", replace: "নশ", rules: nil),
        AvroPattern(find: "Ngr", replace: "ঙর", rules: nil),
        AvroPattern(find: "NGr", replace: "ঞর", rules: nil),
        AvroPattern(find: "ngr", replace: "ংর", rules: nil),
        AvroPattern(find: "nj", replace: "ঞ্জ", rules: nil),
        AvroPattern(find: "Ng", replace: "ঙ", rules: nil),
        AvroPattern(find: "NG", replace: "ঞ", rules: nil),
        AvroPattern(find: "nk", replace: "ঙ্ক", rules: nil),
        AvroPattern(find: "ng", replace: "ং", rules: nil),
        AvroPattern(find: "nn", replace: "ন্ন", rules: nil),
        AvroPattern(find: "NN", replace: "ণ্ণ", rules: nil),
        AvroPattern(find: "Nn", replace: "ণ্ন", rules: nil),
        AvroPattern(find: "nm", replace: "ন্ম", rules: nil),
        AvroPattern(find: "Nm", replace: "ণ্ম", rules: nil),
        AvroPattern(find: "nd", replace: "ন্দ", rules: nil),
        AvroPattern(find: "nT", replace: "ন্ট", rules: nil),
        AvroPattern(find: "NT", replace: "ণ্ট", rules: nil),
        AvroPattern(find: "nD", replace: "ন্ড", rules: nil),
        AvroPattern(find: "ND", replace: "ণ্ড", rules: nil),
        AvroPattern(find: "nt", replace: "ন্ত", rules: nil),
        AvroPattern(find: "ns", replace: "ন্স", rules: nil),
        AvroPattern(find: "nc", replace: "ঞ্চ", rules: nil),
        AvroPattern(find: "n", replace: "ন", rules: nil),
        AvroPattern(find: "N", replace: "ণ", rules: nil),
        AvroPattern(find: "OI`", replace: "ৈ", rules: nil),
        AvroPattern(find: "OU`", replace: "ৌ", rules: nil),
        AvroPattern(find: "O`", replace: "ো", rules: nil),
        AvroPattern(find: "OI", replace: "ৈ", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
            ], replace: "ঐ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "ঐ"),
        ]),
        AvroPattern(find: "OU", replace: "ৌ", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
            ], replace: "ঔ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "ঔ"),
        ]),
        AvroPattern(find: "O", replace: "ো", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
            ], replace: "ও"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "ও"),
        ]),
        AvroPattern(find: "phl", replace: "ফ্ল", rules: nil),
        AvroPattern(find: "pT", replace: "প্ট", rules: nil),
        AvroPattern(find: "pt", replace: "প্ত", rules: nil),
        AvroPattern(find: "pn", replace: "প্ন", rules: nil),
        AvroPattern(find: "pp", replace: "প্প", rules: nil),
        AvroPattern(find: "pl", replace: "প্ল", rules: nil),
        AvroPattern(find: "ps", replace: "প্স", rules: nil),
        AvroPattern(find: "ph", replace: "ফ", rules: nil),
        AvroPattern(find: "fl", replace: "ফ্ল", rules: nil),
        AvroPattern(find: "f", replace: "ফ", rules: nil),
        AvroPattern(find: "p", replace: "প", rules: nil),
        AvroPattern(find: "rri`", replace: "ৃ", rules: nil),
        AvroPattern(find: "rri", replace: "ৃ", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
            ], replace: "ঋ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "ঋ"),
        ]),
        AvroPattern(find: "rrZ", replace: "রর‍্য", rules: nil),
        AvroPattern(find: "rry", replace: "রর‍্য", rules: nil),
        AvroPattern(find: "rZ", replace: "র‍্য", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "r"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "y"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "w"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "x"),
            ], replace: "্র্য"),
        ]),
        AvroPattern(find: "ry", replace: "র‍্য", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "r"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "y"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "w"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "x"),
            ], replace: "্র্য"),
        ]),
        AvroPattern(find: "rr", replace: "রর", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "v", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "r"),
                AvroMatch(type: "s", scope: "p", negative: true, value: ""),
            ], replace: "র্"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "r"),
            ], replace: "্রর"),
        ]),
        AvroPattern(find: "Rg", replace: "ড়্গ", rules: nil),
        AvroPattern(find: "Rh", replace: "ঢ়", rules: nil),
        AvroPattern(find: "R", replace: "ড়", rules: nil),
        AvroPattern(find: "r", replace: "র", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "r"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "y"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "w"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "x"),
                AvroMatch(type: "p", scope: "e", negative: true, value: "Z"),
            ], replace: "্র"),
        ]),
        AvroPattern(find: "shch", replace: "শ্ছ", rules: nil),
        AvroPattern(find: "ShTh", replace: "ষ্ঠ", rules: nil),
        AvroPattern(find: "Shph", replace: "ষ্ফ", rules: nil),
        AvroPattern(find: "Sch", replace: "শ্ছ", rules: nil),
        AvroPattern(find: "skl", replace: "স্ক্ল", rules: nil),
        AvroPattern(find: "skh", replace: "স্খ", rules: nil),
        AvroPattern(find: "sth", replace: "স্থ", rules: nil),
        AvroPattern(find: "sph", replace: "স্ফ", rules: nil),
        AvroPattern(find: "shc", replace: "শ্চ", rules: nil),
        AvroPattern(find: "sht", replace: "শ্ত", rules: nil),
        AvroPattern(find: "shn", replace: "শ্ন", rules: nil),
        AvroPattern(find: "shm", replace: "শ্ম", rules: nil),
        AvroPattern(find: "shl", replace: "শ্ল", rules: nil),
        AvroPattern(find: "Shk", replace: "ষ্ক", rules: nil),
        AvroPattern(find: "ShT", replace: "ষ্ট", rules: nil),
        AvroPattern(find: "ShN", replace: "ষ্ণ", rules: nil),
        AvroPattern(find: "Shp", replace: "ষ্প", rules: nil),
        AvroPattern(find: "Shf", replace: "ষ্ফ", rules: nil),
        AvroPattern(find: "Shm", replace: "ষ্ম", rules: nil),
        AvroPattern(find: "spl", replace: "স্প্ল", rules: nil),
        AvroPattern(find: "sk", replace: "স্ক", rules: nil),
        AvroPattern(find: "Sc", replace: "শ্চ", rules: nil),
        AvroPattern(find: "sT", replace: "স্ট", rules: nil),
        AvroPattern(find: "st", replace: "স্ত", rules: nil),
        AvroPattern(find: "sn", replace: "স্ন", rules: nil),
        AvroPattern(find: "sp", replace: "স্প", rules: nil),
        AvroPattern(find: "sf", replace: "স্ফ", rules: nil),
        AvroPattern(find: "sm", replace: "স্ম", rules: nil),
        AvroPattern(find: "sl", replace: "স্ল", rules: nil),
        AvroPattern(find: "sh", replace: "শ", rules: nil),
        AvroPattern(find: "Sc", replace: "শ্চ", rules: nil),
        AvroPattern(find: "St", replace: "শ্ত", rules: nil),
        AvroPattern(find: "Sn", replace: "শ্ন", rules: nil),
        AvroPattern(find: "Sm", replace: "শ্ম", rules: nil),
        AvroPattern(find: "Sl", replace: "শ্ল", rules: nil),
        AvroPattern(find: "Sh", replace: "ষ", rules: nil),
        AvroPattern(find: "s", replace: "স", rules: nil),
        AvroPattern(find: "S", replace: "শ", rules: nil),
        AvroPattern(find: "oo`", replace: "ু", rules: nil),
        AvroPattern(find: "oo", replace: "ু", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "উ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "উ"),
        ]),
        AvroPattern(find: "o`", replace: "", rules: nil),
        AvroPattern(find: "oZ", replace: "অ্য", rules: nil),
        AvroPattern(find: "o", replace: "", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "v", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "o"),
            ], replace: "ও"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "v", negative: false, value: ""),
                AvroMatch(type: "p", scope: "e", negative: false, value: "o"),
            ], replace: "অ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "অ"),
        ]),
        AvroPattern(find: "tth", replace: "ত্থ", rules: nil),
        AvroPattern(find: "t``", replace: "ৎ", rules: nil),
        AvroPattern(find: "TT", replace: "ট্ট", rules: nil),
        AvroPattern(find: "Tm", replace: "ট্ম", rules: nil),
        AvroPattern(find: "Th", replace: "ঠ", rules: nil),
        AvroPattern(find: "tn", replace: "ত্ন", rules: nil),
        AvroPattern(find: "tm", replace: "ত্ম", rules: nil),
        AvroPattern(find: "th", replace: "থ", rules: nil),
        AvroPattern(find: "tt", replace: "ত্ত", rules: nil),
        AvroPattern(find: "T", replace: "ট", rules: nil),
        AvroPattern(find: "t", replace: "ত", rules: nil),
        AvroPattern(find: "aZ", replace: "অ্যা", rules: nil),
        AvroPattern(find: "AZ", replace: "অ্যা", rules: nil),
        AvroPattern(find: "a`", replace: "া", rules: nil),
        AvroPattern(find: "A`", replace: "া", rules: nil),
        AvroPattern(find: "a", replace: "া", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "আ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "p", scope: "e", negative: true, value: "a"),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "য়া"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "e", negative: false, value: "a"),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "আ"),
        ]),
        AvroPattern(find: "i`", replace: "ি", rules: nil),
        AvroPattern(find: "i", replace: "ি", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ই"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ই"),
        ]),
        AvroPattern(find: "I`", replace: "ী", rules: nil),
        AvroPattern(find: "I", replace: "ী", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঈ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঈ"),
        ]),
        AvroPattern(find: "u`", replace: "ু", rules: nil),
        AvroPattern(find: "u", replace: "ু", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "উ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "উ"),
        ]),
        AvroPattern(find: "U`", replace: "ূ", rules: nil),
        AvroPattern(find: "U", replace: "ূ", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঊ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঊ"),
        ]),
        AvroPattern(find: "ee`", replace: "ী", rules: nil),
        AvroPattern(find: "ee", replace: "ী", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঈ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "ঈ"),
        ]),
        AvroPattern(find: "e`", replace: "ে", rules: nil),
        AvroPattern(find: "e", replace: "ে", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "এ"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "e", negative: true, value: "`"),
            ], replace: "এ"),
        ]),
        AvroPattern(find: "z", replace: "য", rules: nil),
        AvroPattern(find: "Z", replace: "্য", rules: nil),
        AvroPattern(find: "y", replace: "্য", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: true, value: ""),
                AvroMatch(type: "p", scope: "p", negative: true, value: ""),
            ], replace: "য়"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "ইয়"),
        ]),
        AvroPattern(find: "Y", replace: "য়", rules: nil),
        AvroPattern(find: "q", replace: "ক", rules: nil),
        AvroPattern(find: "w", replace: "ও", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
                AvroMatch(type: "s", scope: "v", negative: false, value: ""),
            ], replace: "ওয়"),
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "c", negative: false, value: ""),
            ], replace: "্ব"),
        ]),
        AvroPattern(find: "x", replace: "ক্স", rules: [
            AvroRule(matches: [
                AvroMatch(type: "p", scope: "p", negative: false, value: ""),
            ], replace: "এক্স"),
        ]),
        AvroPattern(find: ":`", replace: ":", rules: nil),
        AvroPattern(find: ":", replace: "ঃ", rules: nil),
        AvroPattern(find: "^`", replace: "^", rules: nil),
        AvroPattern(find: "^", replace: "ঁ", rules: nil),
        AvroPattern(find: ",,", replace: "্‌", rules: nil),
        AvroPattern(find: ",", replace: ",", rules: nil),
        AvroPattern(find: "$", replace: "৳", rules: nil),
        AvroPattern(find: "`", replace: "", rules: nil),
    ]
}
